WRITE_SOB_FRACTION:
 PUSH(FP);
 MOV(FP, SP);
 MOV(R0, FPARG(0));
 MOV(R1, INDD(R0, 1));
 PUSH(R0);
 PUSH(R1);
 CALL(WRITE_INTEGER);
 PUSH(IMM('/'));
 CALL(PUTCHAR);
 DROP(2);
 POP(R0);
 MOV(R1, INDD(R0, 2));
 PUSH(R1);
 CALL(WRITE_INTEGER);
 DROP(1);
 POP(FP);
 RETURN;
