
#include <stdio.h>
#include <stdlib.h>

/* change to 0 for no debug info to be printed: */
#define DO_SHOW 1
#define MEM_START 1

#include "cisc.h"

int main()
{

  START_MACHINE
  JUMP(CONTINUE)

  #include "char.lib"
  #include "io.lib"
  #include "math.lib"
  #include "scheme.lib"
  #include "string.lib"
  #include "system.lib"

CONTINUE:
PUSH(IMM(56))
CALL(MALLOC)
DROP(1)
MOV(ADDR(MEM_START), IMM(T_VOID))
MOV(ADDR(MEM_START + 1), IMM(T_NIL))
MOV(ADDR(MEM_START + 2), IMM(T_BOOL))
MOV(ADDR(MEM_START + 3), IMM(0))
MOV(ADDR(MEM_START + 4), IMM(T_BOOL))
MOV(ADDR(MEM_START + 5), IMM(1))
MOV(ADDR(MEM_START + 6), IMM(T_INTEGER))
MOV(ADDR(MEM_START + 7), IMM(1))
MOV(ADDR(MEM_START + 8), IMM(T_INTEGER))
MOV(ADDR(MEM_START + 9), IMM(2))
MOV(ADDR(MEM_START + 10), IMM(T_PAIR))
MOV(ADDR(MEM_START + 11), IMM(MEM_START + 8))
MOV(ADDR(MEM_START + 12), IMM(MEM_START + 1))
MOV(ADDR(MEM_START + 13), IMM(T_PAIR))
MOV(ADDR(MEM_START + 14), IMM(MEM_START + 6))
MOV(ADDR(MEM_START + 15), IMM(MEM_START + 10))
MOV(ADDR(MEM_START + 16), IMM(T_INTEGER))
MOV(ADDR(MEM_START + 17), IMM(3))
MOV(ADDR(MEM_START + 18), IMM(T_INTEGER))
MOV(ADDR(MEM_START + 19), IMM(4))
MOV(ADDR(MEM_START + 20), IMM(T_INTEGER))
MOV(ADDR(MEM_START + 21), IMM(5))
MOV(ADDR(MEM_START + 22), IMM(T_INTEGER))
MOV(ADDR(MEM_START + 23), IMM(6))
MOV(ADDR(MEM_START + 24), IMM(T_PAIR))
MOV(ADDR(MEM_START + 25), IMM(MEM_START + 22))
MOV(ADDR(MEM_START + 26), IMM(MEM_START + 1))
MOV(ADDR(MEM_START + 27), IMM(T_PAIR))
MOV(ADDR(MEM_START + 28), IMM(MEM_START + 20))
MOV(ADDR(MEM_START + 29), IMM(MEM_START + 24))
MOV(ADDR(MEM_START + 30), IMM(T_INTEGER))
MOV(ADDR(MEM_START + 31), IMM(7))
MOV(ADDR(MEM_START + 32), IMM(T_PAIR))
MOV(ADDR(MEM_START + 33), IMM(MEM_START + 30))
MOV(ADDR(MEM_START + 34), IMM(MEM_START + 1))
MOV(ADDR(MEM_START + 35), IMM(T_PAIR))
MOV(ADDR(MEM_START + 36), IMM(MEM_START + 27))
MOV(ADDR(MEM_START + 37), IMM(MEM_START + 32))
MOV(ADDR(MEM_START + 38), IMM(T_PAIR))
MOV(ADDR(MEM_START + 39), IMM(MEM_START + 18))
MOV(ADDR(MEM_START + 40), IMM(MEM_START + 35))
MOV(ADDR(MEM_START + 41), IMM(T_PAIR))
MOV(ADDR(MEM_START + 42), IMM(MEM_START + 4))
MOV(ADDR(MEM_START + 43), IMM(MEM_START + 1))
MOV(ADDR(MEM_START + 44), IMM(T_PAIR))
MOV(ADDR(MEM_START + 45), IMM(MEM_START + 2))
MOV(ADDR(MEM_START + 46), IMM(MEM_START + 41))
MOV(ADDR(MEM_START + 47), IMM(T_PAIR))
MOV(ADDR(MEM_START + 48), IMM(MEM_START + 38))
MOV(ADDR(MEM_START + 49), IMM(MEM_START + 44))
MOV(ADDR(MEM_START + 50), IMM(T_PAIR))
MOV(ADDR(MEM_START + 51), IMM(MEM_START + 16))
MOV(ADDR(MEM_START + 52), IMM(MEM_START + 47))
MOV(ADDR(MEM_START + 53), IMM(T_PAIR))
MOV(ADDR(MEM_START + 54), IMM(MEM_START + 13))
MOV(ADDR(MEM_START + 55), IMM(MEM_START + 50))

	MOV(R0, IMM(MEM_START + 53))
	MOV(R0, IMM(MEM_START + 1))

  PUSH(R0)
  CALL(WRITE_SOB)
  DROP(1)
  PUSH(IMM('\n'))
  CALL(PUTCHAR)
  DROP(1)
  STOP_MACHINE

  return 0;
}