
#include <stdio.h>
#include <stdlib.h>

/* change to 0 for no debug info to be printed: */
#define DO_SHOW 1
#define MEM_START 1

#include "cisc.h"

int main()
{

  START_MACHINE
  JUMP(CONTINUE)

  #include "char.lib"
  #include "io.lib"
  #include "math.lib"
  #include "scheme.lib"
  #include "string.lib"
  #include "system.lib"

CONTINUE:
PUSH(IMM(46))
CALL(MALLOC)
DROP(1)
MOV(ADDR(MEM_START), IMM(T_VOID))
MOV(ADDR(MEM_START + 1), IMM(T_NIL))
MOV(ADDR(MEM_START + 2), IMM(T_BOOL))
MOV(ADDR(MEM_START + 3), IMM(0))
MOV(ADDR(MEM_START + 4), IMM(T_BOOL))
MOV(ADDR(MEM_START + 5), IMM(1))
MOV(ADDR(MEM_START + 6), IMM(T_STRING))
MOV(ADDR(MEM_START + 6 + 1), IMM(1))
MOV(ADDR(MEM_START + 6 + 2), IMM('B'))
MOV(ADDR(MEM_START + 9), IMM(T_INTEGER))
MOV(ADDR(MEM_START + 10), IMM(3))
MOV(ADDR(MEM_START + 11), IMM(T_SYMBOL))
MOV(ADDR(MEM_START + 11 + 1), IMM(5))
MOV(ADDR(MEM_START + 11 + 2), IMM('q'))
MOV(ADDR(MEM_START + 11 + 3), IMM('u'))
MOV(ADDR(MEM_START + 11 + 4), IMM('o'))
MOV(ADDR(MEM_START + 11 + 5), IMM('t'))
MOV(ADDR(MEM_START + 11 + 6), IMM('e'))
MOV(ADDR(MEM_START + 18), IMM(T_SYMBOL))
MOV(ADDR(MEM_START + 18 + 1), IMM(4))
MOV(ADDR(MEM_START + 18 + 2), IMM('c'))
MOV(ADDR(MEM_START + 18 + 3), IMM('a'))
MOV(ADDR(MEM_START + 18 + 4), IMM('k'))
MOV(ADDR(MEM_START + 18 + 5), IMM('e'))
MOV(ADDR(MEM_START + 24), IMM(T_PAIR))
MOV(ADDR(MEM_START + 25), IMM(MEM_START + 18))
MOV(ADDR(MEM_START + 26), IMM(MEM_START + 1))
MOV(ADDR(MEM_START + 27), IMM(T_PAIR))
MOV(ADDR(MEM_START + 28), IMM(MEM_START + 11))
MOV(ADDR(MEM_START + 29), IMM(MEM_START + 24))
MOV(ADDR(MEM_START + 30), IMM(T_SYMBOL))
MOV(ADDR(MEM_START + 30 + 1), IMM(6))
MOV(ADDR(MEM_START + 30 + 2), IMM('c'))
MOV(ADDR(MEM_START + 30 + 3), IMM('o'))
MOV(ADDR(MEM_START + 30 + 4), IMM('o'))
MOV(ADDR(MEM_START + 30 + 5), IMM('k'))
MOV(ADDR(MEM_START + 30 + 6), IMM('i'))
MOV(ADDR(MEM_START + 30 + 7), IMM('e'))
MOV(ADDR(MEM_START + 38), IMM(T_PAIR))
MOV(ADDR(MEM_START + 39), IMM(MEM_START + 30))
MOV(ADDR(MEM_START + 40), IMM(MEM_START + 1))
MOV(ADDR(MEM_START + 41), IMM(T_PAIR))
MOV(ADDR(MEM_START + 42), IMM(MEM_START + 27))
MOV(ADDR(MEM_START + 43), IMM(MEM_START + 38))
MOV(ADDR(MEM_START + 44), IMM(T_PAIR))
MOV(ADDR(MEM_START + 45), IMM(MEM_START + 9))
MOV(ADDR(MEM_START + 46), IMM(MEM_START + 41))
MOV(ADDR(MEM_START + 47), IMM(T_PAIR))
MOV(ADDR(MEM_START + 48), IMM(MEM_START + 6))
MOV(ADDR(MEM_START + 49), IMM(MEM_START + 44))

	MOV(R0, IMM(MEM_START + 47))

  PUSH(R0)
  CALL(WRITE_SOB)
  PUSH(IMM('\n'))
  CALL(PUTCHAR)
  DROP(2)
  STOP_MACHINE

  return 0;
}